import React from 'react'
import axios from 'axios'
import './AllNotes.css'
import { useEffect } from 'react'
import { useState } from 'react'
import { MdDelete } from "react-icons/md";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  PDFDownloadLink
} from "@react-pdf/renderer";
const AllNotes = ({ cr }) => {
  const [allnotesdata, setallnotesdata] = useState([]);
  const [load, setload] = useState(false);

  useEffect(() => {
    (async () => {
      try {
        const response = await axios.get('/api/fetchnote');
        console.log(response.data);
        setallnotesdata(response.data)

      } catch (error) {
        console.log(error);

      }
    })();
  }, [cr])
 const MyPDF = ({ note }) => (
  <Document>
    <Page
      size="A4"
      style={{
        padding: 25,
        fontSize: 12,
        backgroundColor: "#f5f5f5",
        fontFamily: "Helvetica"
      }}
    >

       
      <View
        style={{
          borderBottom: "2px solid #222",
          marginBottom: 15,
          paddingBottom: 8,
          
        }}
      >
        <Text style={{ fontSize: 18, fontWeight: "bold" }}>
          Lalit Nest
        </Text>
        <Text style={{ fontSize: 10, color: "gray" }}>
          Downloaded on: {new Date().toLocaleDateString()}
        </Text>
      </View>

     
      <View
        style={{
          backgroundColor: "#fff",
          padding: 15,
          borderRadius: 6,
          border: "1px solid #ddd"
        }}
      >
 
        <Text
          style={{
            backgroundColor: "#333",
            color: "#fff",
            padding: 4,
            fontSize: 10,
            borderRadius: 3,
            marginBottom: 10,
            alignSelf: "flex-start"
          }}
        >
          {note.tag}
        </Text>

        
        <Text
          style={{
            fontSize: 16,
            fontWeight: "bold",
            marginBottom: 10
          }}
        >
          {note.title}
        </Text>

       
        <View style={{ flexDirection: "row", marginBottom: 6 }}>
          <Text style={{ width: 60, fontWeight: "bold" }}>
            Date:
          </Text>
          <Text style={{ flex: 1 }}>
            {new Date(note.createdAt).toLocaleDateString("en-IN", {
              day: "2-digit",
              month: "short",
              year: "numeric"
            })}
          </Text>
        </View>

        
        <Text
          style={{
            marginTop: 10,
            lineHeight: 1.5
          }}
        >
          {note.content}
        </Text>
      </View>

       
      <Text
        style={{
          position: "absolute",
          bottom: 20,
          left: 25,
          right: 25,
          borderTop: "1px solid #ccc",
          paddingTop: 5,
          fontSize: 10,
          color: "gray",
          textAlign: "center"
        }}
      >
        Generated by Lalit Nest • Notes Management System
      </Text>

    </Page>
  </Document>
);
  const delete_note = (_id) => {
     setload(true);
    setTimeout(async () => {
      const response = await axios.post('/api/deletenote', { _id });
      console.log(response.data);
      setload(false);
      window.location.reload();

    }, 3000);
  }
  return (
    <div className='all-notes'>
      <section>
        <span className="allnote-heading">
          <img src="/notes (1).png" alt="" />
          <h4>ALL NOTES</h4>
        </span>
        <div className="all-notes-section">
          {allnotesdata.length > 0 ?( allnotesdata.map((i) => (
            <div className="user-notes" style={{ backgroundColor: i.color }} id='myusernotes'>
              <div className="all-details-notes"  >
                <h4>{i.tag}</h4>
                <p className='title-name'>Title : {i.title}</p>
                <p>{i.content}</p>
              </div>
              <div className="edit-delete-pdf">
                <p>{new Date(i.createdAt).toLocaleDateString('en-IN',{
                  day:'2-digit',
                  month:'short',
                  year:'numeric'
                })}</p>
                <button onClick={() => { delete_note(i._id) }}><MdDelete className='icon_10' /></button>
                <PDFDownloadLink
                  document={<MyPDF note={i} />}
                  fileName={`note-${i._id}.pdf`}
                  className='pdf-btn'
                >
                  Download
                </PDFDownloadLink>
              </div>
            </div>

          ))):(<div className='create-note-user'>
                <img src="/notepad.png" alt="" />
                <p>create a new note</p>
          </div>)} 
          {load&&(<div className='delete-loading'><div className="spinner"><p>Deleting</p></div></div>)}
        </div>
      </section>
    </div>
  )
}

export default AllNotes
